import * as Types from '../../../gql/types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type CreateChatSessionMutationVariables = Types.Exact<{
  programId: Types.Scalars['String']['input'];
  mediaChannelId?: Types.InputMaybe<Types.Scalars['String']['input']>;
  anonomousUserId?: Types.InputMaybe<Types.Scalars['String']['input']>;
  message?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;


export type CreateChatSessionMutation = { __typename?: 'Mutation', createProgramChatSession: { __typename?: 'ChatSession', id: string, createdAtISO: string, createdById: string, isUserAnonymous: boolean, updatedAtISO: string, programId: string, mediaChannelId?: string | null, messages: Array<{ __typename?: 'ChatMessage', id: string, status: Types.ChatMessageStatus, createdAtISO: string, updatedAtISO: string, type: Types.ChatMessageType, text: string }> } };


export const CreateChatSessionDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"CreateChatSession"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"programId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"mediaChannelId"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"anonomousUserId"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"message"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createProgramChatSession"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"programId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"programId"}}},{"kind":"Argument","name":{"kind":"Name","value":"mediaChannelId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"mediaChannelId"}}},{"kind":"Argument","name":{"kind":"Name","value":"anonomousUserId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"anonomousUserId"}}},{"kind":"Argument","name":{"kind":"Name","value":"message"},"value":{"kind":"Variable","name":{"kind":"Name","value":"message"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"SessionFragment"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"SessionFragment"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ChatSession"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"createdAtISO"}},{"kind":"Field","name":{"kind":"Name","value":"createdById"}},{"kind":"Field","name":{"kind":"Name","value":"isUserAnonymous"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAtISO"}},{"kind":"Field","name":{"kind":"Name","value":"messages"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"createdAtISO"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAtISO"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"text"}}]}},{"kind":"Field","name":{"kind":"Name","value":"programId"}},{"kind":"Field","name":{"kind":"Name","value":"mediaChannelId"}}]}}]} as unknown as DocumentNode<CreateChatSessionMutation, CreateChatSessionMutationVariables>;